import { readFile, writeFile, mkdir, cp } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
let currentSource;
const escape=s=>s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const inline=s=>escape(s).replace(/`([^`]+)`/g,'<code>$1</code>').replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>').replace(/\[([^\]]+)\]\(([^)]+)\)/g,(_,label,url)=>{if(!/^(https?:|[a-zA-Z0-9./#_-])/.test(url))return label;let href=url;if(!/^https?:|^\//.test(url)){const [file,anchor]=url.split('#'),source=resolve(dirname(currentSource),file);const page=pages.find(([,path])=>resolve(path)===source);if(page)href='/docs/'+(page[0]==='index'?'':page[0]+'.html')+(anchor?'#'+anchor:'');else if(source.includes('/docs/evidence/'))href='/docs/evidence/'+source.split('/docs/evidence/')[1];else if(source.endsWith('/docs/collector-plan.html'))href='/docs/collector-plan.html';else return label;}return `<a href="${href}">${label}</a>`;});
function markdown(text){let out='',code=null,list=null,table=false;const close=()=>{if(list){out+=`</${list}>`;list=null;}if(table){out+='</tbody></table></div>';table=false;}};
for(const line of text.split('\n')){if(line.startsWith('```')){close();if(code===null)code='';else{out+=`<pre><code>${escape(code)}</code></pre>`;code=null;}continue;}if(code!==null){code+=line+'\n';continue;}
if(line.startsWith('|')){if(/^\|[\s:|-]+\|$/.test(line))continue;const cells=line.split('|').slice(1,-1);if(!table){close();out+='<div class="table"><table><thead><tr>'+cells.map(c=>`<th>${inline(c.trim())}</th>`).join('')+'</tr></thead><tbody>';table=true;}else out+='<tr>'+cells.map(c=>`<td>${inline(c.trim())}</td>`).join('')+'</tr>';continue;}
const item=line.match(/^([-*]|\d+\.)\s+(.*)/);if(item){const kind=item[1].endsWith('.')?'ol':'ul';if(list!==kind){close();list=kind;out+=`<${kind}>`;}out+=`<li>${inline(item[2])}</li>`;continue;}close();if(!line.trim())continue;const h=line.match(/^(#{1,6}) (.+)/);if(h){const n=h[1].length,id=h[2].toLowerCase().replace(/[^a-z0-9]+/g,'-');out+=`<h${n} id="${id}">${inline(h[2])}</h${n}>`;}else out+=`<p>${inline(line)}</p>`;}close();return out;}
const pages=[['index','../README.md','Quickstart'],['config','../docs/config.md','Configuration'],['api','../docs/api.md','API'],['self-hosting','../docs/self-hosting.md','Self hosting'],['upgrading','../docs/upgrading.md','Upgrading'],['dependency-upgrade','../docs/dependency-upgrade.md','Dependency upgrade'],['maintenance','../docs/maintenance.md','Maintenance'],['release','../docs/release.md','Release'],['status','../docs/status.md','Plan status'],['validation','../docs/validation.md','Validation'],['acceptance-evidence','../docs/acceptance-evidence.md','Acceptance evidence'],['bench','../bench/README.md','Benchmarks'],['examples','../examples/README.md','Examples'],['spec','../spec/README.md','Wire contract'],['ui','packages/ui/README.md','UI package']];
await mkdir('dist/docs',{recursive:true});await cp('../docs/evidence','dist/docs/evidence',{recursive:true});await cp('../docs/collector-plan.html','dist/docs/collector-plan.html');await writeFile('dist/docs/theme.css',await readFile('packages/ui/dist/theme.css','utf8'));
const css=`body{margin:0;background:var(--background);color:var(--foreground);font:15px/1.65 system-ui}header{padding:20px 4vw;border-bottom:1px solid var(--border);font-weight:800}a{color:inherit}nav{display:flex;gap:14px;flex-wrap:wrap;padding:16px 4vw;background:var(--card)}main{max-width:920px;margin:auto;padding:32px 24px 80px}h1,h2,h3{letter-spacing:-.025em}h2{margin-top:36px}pre{background:var(--muted);border:1px solid var(--border);padding:18px;border-radius:16px;overflow:auto}code{font-family:monospace;font-size:.88em}.table{overflow:auto}table{border-collapse:collapse;width:100%}td,th{padding:10px;text-align:left;border-bottom:1px solid var(--border)}footer{padding:24px 4vw;color:var(--muted-foreground)}`;
for(const [name,path,title]of pages){currentSource=resolve(path);const content=markdown(await readFile(path,'utf8'));await writeFile(`dist/docs/${name}.html`,`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${title} · Signals</title><link rel="stylesheet" href="/docs/theme.css"><style>${css}</style></head><body><header><a href="/">Signals</a> / Documentation</header><nav>${pages.map(([n,,t])=>`<a href="/docs/${n==='index'?'':n+'.html'}">${t}</a>`).join('')}</nav><main>${content}</main><footer>Apache-2.0 · Development contract status is recorded in Plan status.</footer><script>if(matchMedia('(prefers-color-scheme: dark)').matches)document.documentElement.classList.add('dark')</script></body></html>`);}
console.log('Built',pages.length,'embedded documentation pages.');
