use anyhow::{Context, Result};
use std::{fs, path::Path};

fn main() -> Result<()> {
    let check = std::env::args().any(|v| v == "--check");
    let root = Path::new(env!("CARGO_MANIFEST_DIR")).parent().unwrap();
    let source = root.join("spec/events.schema.json");
    let schema = serde_json::from_str(&fs::read_to_string(&source)?)?;
    let mut space = typify::TypeSpace::default();
    space
        .add_root_schema(schema)
        .context("generate event schema types")?;
    let syntax = syn::parse2(space.to_stream())?;
    let code=format!("// Generated by cargo run -p signals-xtask. Do not edit.\n// Source: spec/events.schema.json (provisional until signals-spec is supplied).\n{}",prettyplease::unparse(&syntax));
    use std::io::Write;
    let mut formatter = std::process::Command::new("rustfmt")
        .args(["--edition", "2021", "--emit", "stdout"])
        .stdin(std::process::Stdio::piped())
        .stdout(std::process::Stdio::piped())
        .spawn()?;
    formatter.stdin.take().unwrap().write_all(code.as_bytes())?;
    let output = formatter.wait_with_output()?;
    anyhow::ensure!(output.status.success(), "Format generated types");
    let code = String::from_utf8(output.stdout)?;
    let target = root.join("crates/signals-core/src/wire.rs");
    if check {
        anyhow::ensure!(
            fs::read_to_string(&target)? == code,
            "Generated event types are stale; run cargo run -p signals-xtask"
        );
    } else {
        fs::write(target, code)?;
    }
    Ok(())
}
